### ISSUE TITLE
Does this repo contain virus code?

### ISSUE THREAD

**Issue by diyseguy** [TheParmak/conti-leaks-englished#21]
I downloaded the code and uploaded it to Virustotal and it reports back 4 bad things:

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/27981142/156689163-d10fbd74-25c4-4597-992e-c5b9804b8a04.png">

Is this something to be expected?

**Comment by TheParmak** [comment]
This repo contains conti ransomware groups leaked files so yes this is expected. Also do not download these files if you don't know what you are downloading.

**Comment by TheParmak** [comment]
I am closing the issue in 5 minutes if you don't have any more questions.

**Comment by diyseguy** [comment]
Ok, I thought it was just chat logs, but now I am afraid of it. :0
