### ISSUE TITLE
Combined json is missing 2022 logs

### ISSUE THREAD

**Issue by morriscode** [TheParmak/conti-leaks-englished#5]
https://github.com/TheParmak/conti-leaks-englished/blob/master/deepl/json/translated/combined_en-US.json

I don't see the 2022 chats in this file.

**Comment by TheParmak** [comment]
I just checked and there is 2022 chats there. Can you share the file size and the last 10 lines of the file you have?

**Comment by morriscode** [comment]
Apologies I just pulled it again and you're correct they're present!

**Comment by TheParmak** [comment]
No problem.
