### ISSUE TITLE
 conti-leaks-englished/deepl/json/translated/combined_en-US.json

### ISSUE THREAD

**Issue by 0x241B** [TheParmak/conti-leaks-englished#6]
The file 'conti-leaks-englished/deepl/json/translated/combined_en-US.json' is invalid JSON. I have tried to fix it myself but it is thousands of errors. Could we get a reupload?

**Comment by 0x241B** [comment]
The file 'conti-leaks-englished/deepl/json/translated/combined_en-US.json' is invalid JSON. I have tried to fix it myself but it is thousands of errors. Could we get a reupload?

**Comment by TheParmak** [comment]
I am taking a look, thanks for notifying.

**Comment by Nathannaelc** [comment]
Hey, yeah it's invalid because of the splitting. I'm trying to translate the JSONs one by one right now.

**Comment by TheParmak** [comment]
isn't removing all \n 's  solves it?

**Comment by 0x241B** [comment]
> isn't removing all \n 's solves it?

Unfortunately not. There are formatting issues like below: 

```
{
  }, "ts": "2022-02-27T19:19:45.870724",
  { "from": "pumba@q3mcco35auwcstmt.onion",
  { "to": "tramp@q3mcco35auwcstmt.onion",
  { "body": "say I'll take her under special control"
}
```

As well as things like double quotes in the body text not being escaped, and other slashes not being escaped.

**Comment by TheParmak** [comment]
oh, I see.

**Comment by Nathannaelc** [comment]
It took longer than expected. Some files throw the "appears to already be in English" error. Just letting you know, don't fix that JSON.

**Comment by TheParmak** [comment]
What do you mean don't fix that JSON? did you fixed it, are you fixing it or is it just not fixable?

**Comment by Nathannaelc** [comment]
I'm retranslating the whole thing one by one. it technically is fixable but will require unnecessary amount of time.

**Comment by TheParmak** [comment]
Do you have any,  more convenient way to speak? like discord, twitter, or even netcat.

**Comment by Nathannaelc** [comment]
Damn, seems like Deepl removed some of the commas. I'll do a PR anyway.

**Comment by TheParmak** [comment]
can't you parse the untranslated json first, extract the body, translate it, and then merge with original json?

**Comment by Nathannaelc** [comment]
That's easy. Doing it right now
.

**Comment by TheParmak** [comment]
https://en.meming.world/images/en/4/4a/Modern_Problems_Require_Modern_Solutions.jpg

**Comment by Nathannaelc** [comment]
Translated body in #7
